/**
 * Constants used throughout the app for event names.
 */
module.exports = Object.freeze({
  CELL_UPDATE: 'CELL_UPDATE',
  GAME_UPDATE: 'GAME_UPDATE',

  VALIDATE_GRID: 'VALIDATE_GRID',
  VALIDATE_ROW: 'VALIDATE_ROW',
  VALIDATE_COLUMN: 'VALIDATE_COLUMN',

  INVALIDATE_GRID: 'INVALIDATE_GRID',
  INVALIDATE_ROW: 'INVALIDATE_ROW',
  INVALIDATE_COLUMN: 'INVALIDATE_COLUMN',

  WON: 'WON'
});